name: course_downloader
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4=4.6.3
  - python=3.5.3
  - requests
  - setuptools
  - six
  - pip
  - youtube-dl=2018.9.26
  - pyinstaller
  - pefile>=2017.8.1
  - pip:
    - fbs
    - PyQt5==5.9.2


