name: course_downloader
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4=4.6.3=py35_0
  - python=3.5.3=3
  - requests
  - setuptools=40.2.0=py35_0
  - six=1.11.0=py35_1
  - pip=10.0.1=py35_0
  - youtube-dl=2018.9.26=py35_0
  - pyinstaller=3.4
  - pip:
    - fbs
    - PyQt5==5.9.2


